### ISSUE TITLE
Use objc_id to handle managing Objective-C objects

### ISSUE THREAD

**Issue by jrmuizel** [gfx-rs/metal-rs#29]
I noticed that metal-rs is using its own infrastructure (foreign_obj_type!) for managing Objective-C objects instead of objc_id. I was wondering if there was a particular reason for this and if the metal-rs strategy is better for some reason.

@JohnColanduoni

**Comment by JohnColanduoni** [comment]
Metal returns a lot of unretained pointers in hot paths (via ObjC's "get" rule) to avoid unnecessary retain/release cycles and using `objc-id` for all the types would make this difficult. For example, `ToOwned` could not be implemented for a Metal type T since objc-id does not implement `Borrow<T>`.

The `foreign_obj_type!` is just a convenience wrapper over `foreign_type!` from the [foreign_types](https://docs.rs/foreign-types/0.3.2/foreign_types/) crate. It is used in most of the `Core*` bindings from the Servo team, which was the impetus for using it here.

**Comment by mjadczak** [comment]
Seems this has been answered, @jrmuizel can you close it if that makes sense to you?

**Comment by jrmuizel** [comment]
Yeah, this makes sense.
