### ISSUE TITLE
Document memory behaviour of command buffers, buffers etc.

### ISSUE THREAD

**Issue by kasper0406** [gfx-rs/metal-rs#96]
This issue may not be related specifically to `metal-rs`, but may be more of a `metal`/`cocoa` rust thing. I'm filing it here, because I'm running into some troubles getting memory deallocation of Metal buffers working, and I haven't been able to solve it using existing resources online.

Ask: It would be very helpful having some more advanced examples of how to manage buffer memory in more complicated scenarios.

Concretely I'm trying to implement a matrix and operations on matrices utilising Metal. The code is currently in a state where it seems to produce correct results, but the application memory seems to increase more or less linearly with the number of operations performed (currently most operations will allocate a new matrix).
In my code I've chosen to have the data of the matrices living solely on the GPU using the StorageModePrivate flag on the buffer, in hope that the data won't needed to be synchronised to the CPU all the time. When transferring data to/from the CPU, I allocate a temporary `CPUCacheModeDefaultCache` buffer and use the Metal API to copy between the two buffers (see https://github.com/kasper0406/neuralnetwork/blob/master/src/metalmatrixhandle.rs#L424). What I currently don't understand is how to properly deallocate the memory associated with both the private and the temporary buffer.

I am wrapping the entire application in a `NSAutoreleasePool`, however this only seems to actually free anything when the pool is released, which does not happen frequently enough when doing many matrix allocations.
The private matrix buffer should basically follow the lifetime of the `MetalMatrixHandle` object. These may not live in some well-defined scope in the code, making it hard to use additional `NSAutoreleasePool`s to handle it.

I have tried calling `retain`/`release` directly on the buffers, but it doesn't really seem to do any deallocation (inspecting by looking at the memory consumption when debugging through Xcode), and also I'm unsure how this behaves when a buffer is queued up for use in a command buffer. I've tried testing the above using a loop allocating buffers that can basically be freed right after they are constructed https://github.com/kasper0406/neuralnetwork/blob/master/src/metalmatrixhandle.rs#L593.

**Comment by kvark** [comment]
So your problem is that buffers are not freed properly? Here are some thoughts:
  - this crate is responsible to give you the object or reference that you can properly clone or drop without touching the refcounts directly. As far as I know, buffer logic here is correct: creating a buffer gives you a retained object `Buffer`, dropping it releases the counter.
  - Metal runtime can have additional references to your buffers, i.e. when used in a command buffer copy operation. I would expect the references to be released sometime at the callback of command buffer that finishes execution on the GPU
  - you can have nested `NSAutoreleasePool` to release more rapidly
  - finally, macOS Instruments have great tooling to show you which objects leak, which are zombies, where the retains/releases are, etc.

**Comment by kasper0406** [comment]
Thanks for the explanation and pointers for debugging @kvark.
I changed to code to be more aggressive in creating `NSAutoreleasePool`'s and the seems to do the trick well enough.
